### ISSUE TITLE
[BUG] Error loading template

### ISSUE THREAD

**Issue by mosc9575** [somesh101/JupyterTemplates#1]
Loading the template `basic.ipynb` which was shipped with the extension raises an error `Error: NotebookCellData MUST have 'value' property`.

Traceback:
```
Error loading template basic.ipynb: Error: NotebookCellData MUST have 'value' property
	at Ri.validate (c:\Users\mosc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:46033)
	at new Ri (c:\Users\mosc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:46483)
	at c:\Users\mosc\.vscode\extensions\someshkumar.jupyter-templates-0.0.4\extension.js:40:30
	at Array.map (<anonymous>)
	at c:\Users\mosc\.vscode\extensions\someshkumar.jupyter-templates-0.0.4\extension.js:24:48
	at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
```

This is because the extension JupyterTemplates saves the `source` of a cell as string. Even if it is a multi line cell. For example

```
{
  "cells": [
    {
      "cell_type": "code",
      "source":  "# this is template file for basic data analysis\n"import pandas as pd\nimport numpy as np\n",
      "metadata": {},
      "position": 0
    },
  ],
}
```

for can be opend again with JupyterTemplates.

The original version where `source` is a list of string doesn't work.

```
{
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "# this is template file for basic data analysis\n",
        "import pandas as pd\n",
        "import numpy as np\n"
      ],
      "metadata": {},
      "position": 0
    },
  ]
}
```

<details><summary>Software version</summary>
Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
</details>

**Comment by somesh101** [comment]
thanks for informing me. 
I am already working on enhancements. This did come in my work and I have fixed it. I am checking if the source is an array or string.
I haven't posted the update because the markdown cells are not formatted properly even though they have the same properties.
I have added my issue here. let's see if someone responds or not.
